all: main.cpp Utilities.cpp MatMatMultiply.cpp MatMatMultiplyBlockHelper.o
	icc main.cpp Utilities.cpp MatMatMultiply.cpp MatMatMultiplyBlockHelper.o -xHost -mkl -qopenmp

MatMatMultiplyBlockHelper.o: MatMatMultiplyBlockHelper.cpp
	icc -c MatMatMultiplyBlockHelper.cpp -xHost -fno-alias

assembly: MatMatMultiplyBlockHelper.cpp
	icc -S MatMatMultiplyBlockHelper.cpp -xHost -fno-alias

clean:
	rm a.out *.s *.o

